{{-- ══════════════════════════════════════════════════
     TOP MENU — TOONWORLD Neo-Brutalist Style
══════════════════════════════════════════════════ --}}

<div class="top-menu-wrap border-b-4 border-black dark:border-white bg-[#FFFBEA] dark:bg-black py-2 px-3 z-40">
    <div class="container-fluid">

        {{-- Desktop horizontal list --}}
        <div class="top-menu-scroll d-none d-md-block flex-grow-1">
            <ul class="top-menu-list flex items-center gap-2 font-fredoka font-extrabold overflow-x-auto py-1">
                <li>
                    <a href="{{ route('dashboard') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('dashboard') || request()->routeIs('super-admin.dashboard') ? '!bg-[#FFE600] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#FFE600] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}">
                        <span>📊 Dasbor</span>
                    </a>
                </li>

                @if(auth()->user()->isSuperAdmin())
                    <li><a href="{{ route('project-requests.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('project-requests.index') ? '!bg-[#FFE600] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#FFE600] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>🎫 Tiket</span></a></li>
                    <li><a href="{{ route('super-admin.reports') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('super-admin.reports*') ? '!bg-[#0055FF] !text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#0055FF] hover:!text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>📑 Laporan</span></a></li>
                    <li><a href="{{ route('super-admin.reports.technical') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('super-admin.reports.technical') ? '!bg-[#FF6B00] !text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#FF6B00] hover:!text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>🛠️ Laporan Teknis</span></a></li>
                    <li><a href="{{ route('super-admin.users.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('super-admin.users.*') ? '!bg-[#00E676] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#00E676] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>👥 Pengguna & Aset</span></a></li>
                    <li><a href="{{ route('super-admin.activity-logs') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('super-admin.activity-logs') ? '!bg-[#9000FF] !text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#9000FF] hover:!text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>📚 Activity Logs</span></a></li>
                    <li><a href="{{ route('super-admin.settings') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('super-admin.settings') ? '!bg-[#FFE600] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#FFE600] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>⚙️ Pengaturan</span></a></li>

                @elseif(auth()->user()->canApproveProjects())
                    <li><a href="{{ route('queues.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('queues.*') ? '!bg-[#FF007A] !text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#FF007A] hover:!text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>📋 Antrian</span></a></li>
                    <li><a href="{{ route('approvals.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('approvals.*') ? '!bg-[#00E676] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#00E676] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>✅ Persetujuan</span></a></li>
                    <li><a href="{{ route('project-requests.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('project-requests.index') ? '!bg-[#FFE600] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#FFE600] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>🎫 Semua Tiket</span></a></li>
                    <li><a href="{{ route('chat.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('chat.*') ? '!bg-[#FF6B00] !text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#FF6B00] hover:!text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>💬 Chat</span></a></li>
                    <li><a href="{{ route('daily-logs.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('daily-logs.*') ? '!bg-[#9000FF] !text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#9000FF] hover:!text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>📝 Log Harian</span></a></li>
                @elseif(auth()->user()->isDeveloper())
                    <li><a href="{{ route('project-requests.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('project-requests.index') ? '!bg-[#FFE600] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#FFE600] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>🎫 Tiket Saya</span></a></li>
                    <li><a href="{{ route('chat.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('chat.*') ? '!bg-[#0055FF] !text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#0055FF] hover:!text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>💬 Chat</span></a></li>
                    <li><a href="{{ route('daily-logs.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('daily-logs.*') ? '!bg-[#00E676] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#00E676] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>📝 Log Harian</span></a></li>
                @elseif(auth()->user()->isClient())
                    <li><a href="{{ route('project-requests.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('project-requests.index') ? '!bg-[#FFE600] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#FFE600] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>🎫 Tiket Saya</span></a></li>
                    <li><a href="{{ route('project-requests.create') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('project-requests.create') ? '!bg-[#00E676] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#00E676] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>➕ Buat Tiket</span></a></li>
                    <li><a href="{{ route('chat.index') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('chat.*') ? '!bg-[#0055FF] !text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#0055FF] hover:!text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>💬 Chat Support</span></a></li>
                @endif

                <li><a href="{{ route('profile.edit') }}" class="top-menu-link px-4 py-2 rounded-2xl border-3 border-black text-sm flex items-center gap-1.5 transition-all {{ request()->routeIs('profile.*') ? '!bg-[#FFE600] !text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] scale-105' : 'bg-white dark:bg-[#1a1a1a] !text-black dark:!text-white hover:!bg-[#FFE600] hover:!text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]' }}"><span>👤 Profil</span></a></li>
            </ul>
        </div>

        {{-- Mobile Active Label --}}
        <div class="d-md-none flex items-center justify-between py-1">
            <span class="font-fredoka font-black text-base text-black dark:text-white uppercase bg-[#FFE600] text-black px-3 py-1 rounded-xl border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                📍 {{ $pageLabel ?? 'Dasbor' }}
            </span>
        </div>
    </div>
</div>
